blank_issues_enabled: false
contact_links:
  - name: Questions on GitHub Discussions
    url: https://github.com/pegasus-isi/cybershake-tools/discussions
    about: Ask questions about your own experiments on the Discussions tab.
  - name: Questions on Slack or Email
    url: https://cybershake-tools.readthedocs.io/en/latest/about/contact.html
    about: Ask questions about your own experiments on our Slack.
