blank_issues_enabled: false
contact_links:
  - name: Questions on GitHub Discussions
    url: https://github.com/SCECcode/cybershake-tools/discussions
    about: Ask questions about your own experiments on the Discussions tab.
